/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.java.coffee_management.view.*;

/**
 *
 * @author ANH TUAN
 */
public class Sell extends javax.swing.JFrame {

    /**
     * Creates new form Sell1
     */
    public Sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSell318 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTable1318 = new javax.swing.JButton();
        btnTable2318 = new javax.swing.JButton();
        btnTable3318 = new javax.swing.JButton();
        btnTable4318 = new javax.swing.JButton();
        btnTable5318 = new javax.swing.JButton();
        btnTable6318 = new javax.swing.JButton();
        btnTable7318 = new javax.swing.JButton();
        btnTable8318 = new javax.swing.JButton();
        btnTable9318 = new javax.swing.JButton();
        btnTable10318 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboBoxFloor318 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSell318.setPreferredSize(new java.awt.Dimension(927, 583));
        panelSell318.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(410, 580));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/sell2.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 580));

        panelSell318.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 0, 387, 586));

        jPanel4.setBackground(new java.awt.Color(69, 32, 16));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(69, 32, 16));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 20, 20));

        btnTable1318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable1318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable1318.setText("1");
        jPanel2.add(btnTable1318);

        btnTable2318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable2318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable2318.setText("2");
        btnTable2318.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTable2318ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTable2318);

        btnTable3318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable3318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable3318.setText("3");
        jPanel2.add(btnTable3318);

        btnTable4318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable4318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable4318.setText("4");
        jPanel2.add(btnTable4318);

        btnTable5318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable5318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable5318.setText("5");
        jPanel2.add(btnTable5318);

        btnTable6318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable6318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable6318.setText("6");
        btnTable6318.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTable6318ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTable6318);

        btnTable7318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable7318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable7318.setText("7");
        jPanel2.add(btnTable7318);

        btnTable8318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable8318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable8318.setText("8");
        jPanel2.add(btnTable8318);

        btnTable9318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable9318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable9318.setText("9");
        btnTable9318.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTable9318ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTable9318);

        btnTable10318.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnTable10318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Table (1).png"))); // NOI18N
        btnTable10318.setText("10");
        jPanel2.add(btnTable10318);

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 123, 358, 326));

        jPanel5.setBackground(new java.awt.Color(69, 32, 16));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Free");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Serving");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 64, 52, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Reserved");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 31, -1, -1));
        jPanel5.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, 58, -1));
        jPanel5.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 58, -1));
        jPanel5.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 31, 58, -1));

        jLabel1.setBackground(new java.awt.Color(69, 32, 16));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffeemanagement/image/logo.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 13, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 446, 360, 140));

        comboBoxFloor318.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxFloor318.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));
        comboBoxFloor318.setBorder(null);
        jPanel4.add(comboBoxFloor318, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 14, 155, 55));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tầng:");
        jLabel2.setPreferredSize(new java.awt.Dimension(67, 22));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 14, -1, 66));

        panelSell318.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 586));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSell318, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSell318, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTable2318ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTable2318ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTable2318ActionPerformed

    private void btnTable9318ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTable9318ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTable9318ActionPerformed

    private void btnTable6318ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTable6318ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTable6318ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Sell().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTable10318;
    private javax.swing.JButton btnTable1318;
    private javax.swing.JButton btnTable2318;
    private javax.swing.JButton btnTable3318;
    private javax.swing.JButton btnTable4318;
    private javax.swing.JButton btnTable5318;
    private javax.swing.JButton btnTable6318;
    private javax.swing.JButton btnTable7318;
    private javax.swing.JButton btnTable8318;
    private javax.swing.JButton btnTable9318;
    private javax.swing.JComboBox<String> comboBoxFloor318;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelSell318;
    // End of variables declaration//GEN-END:variables
}
