/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.coffee_management.view;

/**
 *
 * @author ANH TUAN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu318 = new javax.swing.JPanel();
        Panel2_318 = new javax.swing.JPanel();
        JLabel = new javax.swing.JLabel();
        Panel3_318 = new javax.swing.JPanel();
        Panel4_318 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu318.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2_318.setPreferredSize(new java.awt.Dimension(140, 344));
        Panel2_318.setLayout(null);
        panelMenu318.add(Panel2_318, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        JLabel.setBackground(new java.awt.Color(69, 32, 16));
        JLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabel.setForeground(new java.awt.Color(253, 253, 253));
        JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel.setText("                          Chọn món");
        JLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        JLabel.setIconTextGap(7);
        JLabel.setOpaque(true);
        panelMenu318.add(JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 280, 30));

        Panel3_318.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Panel3_318.setPreferredSize(new java.awt.Dimension(289, 420));

        javax.swing.GroupLayout Panel3_318Layout = new javax.swing.GroupLayout(Panel3_318);
        Panel3_318.setLayout(Panel3_318Layout);
        Panel3_318Layout.setHorizontalGroup(
            Panel3_318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Panel3_318Layout.setVerticalGroup(
            Panel3_318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        panelMenu318.add(Panel3_318, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/coffee_management/image/Food & drink (1).png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 47));

        javax.swing.GroupLayout Panel4_318Layout = new javax.swing.GroupLayout(Panel4_318);
        Panel4_318.setLayout(Panel4_318Layout);
        Panel4_318Layout.setHorizontalGroup(
            Panel4_318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel4_318Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        Panel4_318Layout.setVerticalGroup(
            Panel4_318Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel4_318Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        panelMenu318.add(Panel4_318, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 280, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu318, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu318, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JPanel Panel2_318;
    private javax.swing.JPanel Panel3_318;
    private javax.swing.JPanel Panel4_318;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelMenu318;
    // End of variables declaration//GEN-END:variables
}
